### ISSUE TITLE
contentCardsHandler not called on Android

### ISSUE THREAD

**Issue by douglashetherington** [braze-inc/braze-flutter-sdk#12]
Hi folks,

plugin: 2.2.0

I'm testing by sending test messages from the braze ui, to my customer id.

I've got content cards (flutter side) and in app messages (native) working nicely on iOS. - This works perfectly.

On android I neither the `contentCardsHandler` nor the `inAppMessageHandler` seem to get called although the (native) in app messages work fine.

Setting braze logging to 0 I can see that it's receiving the commands from braze. Things like:
`/Braze v16.0.0 .com.braze.push.BrazeFirebaseMessagingService(11489): Got remote message from FCM: {a=Your Content Card is now available and will expire in five minutes., p=0, t=Braze Test Send, _ab=true, cid=dGVzdF90ZXN0X2R43242341111243NTgwNzcxZWZlNjlhNGZiNDdkNjll, ab_cd={"uw":null,`

I'm also getting called on the FirebaseMessaging.onMessage callback. So it seems like it's making it's way to the app but it's like I'm missing some kind of registering the plugin for the notifications or something?

Any ideas?

**Comment by Bucimis** [comment]
Hi @douglashetherington, is your use case to receive in-app messages and Content Cards and show them manually using a custom Flutter UI (as opposed to the Braze native UI)?

In that case, due to an issue with the latest release, I would recommend the following:

1. Disable the automatic integration initializer feature using `com_braze_flutter_enable_automatic_integration_initializer` as described in https://github.com/braze-inc/braze-flutter-sdk/blob/master/CHANGELOG.md#220

2. Implement in-app message and Content Cards callbacks manually (as you did on iOS) following these instructions:
https://github.com/braze-inc/braze-flutter-sdk/tree/487384e8eba9e81c1ac42a4475cd7ef6031f9c78#in-app-message-data-callback

3. Add your call to `registerActivityLifecycleCallbacks()` manually as described in https://github.com/braze-inc/braze-flutter-sdk/tree/487384e8eba9e81c1ac42a4475cd7ef6031f9c78#android

If after you do the following, you still don't receive data in your callbacks after calling `BrazePlugin.setBrazeInAppMessageCallback()` and `BrazePlugin.setBrazeContentCardsCallback()`, feel free to raise to support@braze.com with full verbose logs so we can debug more deeply.

**Comment by douglashetherington** [comment]
Thanks for the super quick answer @Bucimis. What we want is a kind of hybrid. The native inappmessaging is perfect for what we need. So we'd like to use that. For the content cards though we need to inject those into our existing dashboard so we'd like to handle those on the flutter side. Does that sound like the above work with that?

**Comment by Bucimis** [comment]
@douglashetherington No problem! What you described should work, but you would need to use the solution I outlined above minus the in-app message callback part if you don't need to pass in-app message data into the Flutter layer.

**Comment by hokstuff** [comment]
Hi @douglashetherington,

We have just released [Flutter SDK version 2.3.0](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/2.3.0) which allows you to customize whether or not to handle the in-app message in the Flutter layer on Android. That way you don't need to use the workaround [described here](https://github.com/braze-inc/braze-flutter-sdk/issues/12#issuecomment-986458192). To read more about it, you can reference [the public docs here](https://www.braze.com/docs/developer_guide/platform_integration_guides/flutter/inapp_messages/#disabling-automatic-display).

Thanks and feel free to reopen if you're still experiencing issues!
