### ISSUE TITLE
Content card methods need return values/error reporting

### ISSUE THREAD

**Issue by derekpitts28** [braze-inc/braze-flutter-sdk#3]
I am attempting to use the content card methods however I do not have the ability to know if they failed or passed other than a print out in the console. Can you please add the boolean return type that is already there or even better, return the error when applicable. See code below for what I would like updated:

BrasePLugin.kt
```
        "logContentCardClicked" -> {
          val contentCardString = call.argument<String>("contentCardString")
          if (contentCardString != null) {
            val contentCard = Braze.getInstance(context).deserializeContentCard(contentCardString)
            if (contentCard != null) {
              result.success(contentCard.logClick()) **// ADD RESULT.SUCCESS**
            }
          }
        }
        "logContentCardImpression" -> {
          val contentCardString = call.argument<String>("contentCardString")
          if (contentCardString != null) {
            val contentCard = Braze.getInstance(context).deserializeContentCard(contentCardString)
            if (contentCard != null) {
              result.success(contentCard.logImpression())) **// ADD RESULT.SUCCESS**
            }
          }
        }
        "logContentCardDismissed" -> {
          val contentCardString = call.argument<String>("contentCardString")
          if (contentCardString != null) {
            val contentCard = Braze.getInstance(context).deserializeContentCard(contentCardString)
            if (contentCard != null) {
              result.success(contentCard.setIsDismissed(true))) **// ADD RESULT.SUCCESS**
            }
          }
        }
```

This is currently causing us headaches for custom content card implementations.

Thanks!

Derek

**Comment by Bucimis** [comment]
Hi @derekpitts28,

Thanks for getting in touch. What's your use case for knowing about success/failure of these calls, is it for debugging, user-visible errors, etc.?

The success/failure return values for `logImpression()` on Android only guarantee that the SDK will try to log an impression event and mark the current card as visually read in the UI. Other methods have similar guarantees. There's no way to get an end-to-end guarantee that an impression was logged with the Braze server, which is why we generally recommend people to "fire and forget" their calls to methods like `logImpression()` (i.e. assume success every time).

Also, the Braze iOS SDK's analogous methods all return `void` so won't be able to offer that functionality on iOS either way.

**Comment by derekpitts28** [comment]
No worries I was attempting to cache failed logDismiss event but I realized that the sdk caches them for when the network is reacquired is that correct? Also does the caching mechanism for offline content card logging persist app restart?

**Comment by Bucimis** [comment]
@derekpitts28 yep, all of that is handled for you :)

**Comment by derekpitts28** [comment]
Awesome, thanks for the quick replies!
