### ISSUE TITLE
In App Messages Click Events Do Not Work

### ISSUE THREAD

**Issue by rayliverified** [braze-inc/braze-flutter-sdk#47]
Open URL, deeplink, or open in WebView in app do not work for me.

![snap_screen_20230327193035](https://user-images.githubusercontent.com/19896174/228096319-a6817847-7704-4e5d-8cde-974b5b28982e.png)

Clicking on the button in my app does nothing but close the in app message.

**Comment by hokstuff** [comment]
Hi @rayliverified,

We do support redirecting to custom URLs after clicking on an in-app message when using our Flutter SDK. Can you contact support@braze.com with more information on your integration, the campaign, the version you are using, verbose logging, etc and they will try to reproduce and help you out?

Thanks!

**Comment by rayliverified** [comment]
Thank you for the quick reply Daniel! 

It's great to hear that opening URLs is supported by the Flutter SDK. I'll reach out to support to see what's happening.

Here, you can see nothing happens when the buttons are clicked. 
https://user-images.githubusercontent.com/19896174/228099090-2632863f-c182-4216-bd70-a0dac8173382.mp4

**Comment by rayliverified** [comment]
@hokstuff 
I have some initial information on what is causing the issue and I believe it points to the Braze SDK or there's some integration information I'm missing.

2 issues I'm seeing:
- No IAM links work.
- Push Notification deeplinks are not opening the deeplink intent when the app is closed.

The issue is likely the deeplink intent isn't authored correctly when sent to the app.

Push notification is received when app is closed. This notification opens the BrazePushReceiver when clicked.
> Received broadcast message. Message: Intent { act=com.appboy.action.APPBOY_PUSH_CLICKED cmp=com.treatmyocd.nocd.qa/com.braze.push.BrazePushReceiver (has extras) }

The BrazePushReceiver is responsible for resolving whether to open a URL, another app, URL in the app, or deeplink. It authors the intent to open the main app with. 
> {act=android.intent.action.VIEW dat=https://api-qa.treatmyocd.com/... pkg=com.treatmyocd.nocd.qa cmp=com.treatmyocd.nocd.qa/com.treatmyocd.nocd.MainActivity (has extras)} from uid 10458

The deeplink that is authored likely isn't passing the URL correctly.

**Comment by rayliverified** [comment]
This is the line that creates the intent. It is likely not creating the app start intent correctly.

https://github.com/braze-inc/braze-android-sdk/blob/6d8e477442eaf1410cafce4212b3174e462daf85/android-sdk-ui/src/main/java/com/braze/push/BrazeNotificationUtils.kt#L169

**Comment by hokstuff** [comment]
Hi @rayliverified,

Are you still experiencing this issue? I know a Support case was opened with our team and was checking in if it was resolved already, or if you have more information so they could continue with the investigation.

Thanks!

**Comment by rayliverified** [comment]
Yup, thanks for asking. There's a lot so that's on my backlog right now.

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity and since we are already conversing via the Support channels about your specific setup. Feel free to add more information on those Support threads when you have more details - thanks!

**Comment by favazHF** [comment]
Hi @rayliverified @hokstuff Is there any news on how you fixed this issue?, it is happening with the latest version of Braze for flutter (6.0.0).

**Comment by rayliverified** [comment]
This was never fixed. It still doesn't work.

**Comment by hokstuff** [comment]
Hi @rayliverified,

Can you send additional information around your integration code to the Support team so we can look into your integration more in depth? Also, can you provide specific steps to repro, including which platform(s) you are experiencing issues? It would also help if you can add logging into the methods you'd expect to be called and send it alongside the other information. (Also note that on iOS, many use-cases for push notifications can't be tested on a simulator and needs to be tested on a device.)

The Flutter push integration currently [is done in the native layers](https://www.braze.com/docs/developer_guide/platform_integration_guides/flutter/push_notifications) by following each platform's integration steps separately. This means that the code will live outside of the Dart files and in Swift/Kotlin/etc instead, and each platform has its own set up to be able to open deeplinks or URLs.

Thanks!

**Comment by rayliverified** [comment]
I was able to reproduce this with your example app. I can record a video demoing what I'm seeing.

**Comment by hokstuff** [comment]
Hi @rayliverified,

We have been unable to reproduce the issue in the [Runner sample app](https://github.com/braze-inc/braze-flutter-sdk/tree/master/example) for in-app messages with URLs on iOS and Android, since we are able to successfully open a linked URL inside a webview or by forwarding to an external browser.

For deeplinking, that is not currently integrated in the sample app so it is expected that deeplinks will simply open the app and not forward to any specific page. Please contact the existing Support thread with the information requested above or start a new thread with support@braze.com so we can look into your issue.

Thanks!

**Comment by favazHF** [comment]
Hi @hokstuff, I contacted braze support, commenting that I set up an IAM with an action button and also selecting the Deeplink to App option, when testing with my user the IAM is displayed correctly but when I press the action button it does nothing (just closes the IAM) which is not expected behaviour.

I tried to look for some example or related documentation to be able to capture natively this action but there is nothing.

From support they shared me an example but it was related to Push Notifications but I need IAM.

Any idea how to solve it? Thanks.

<img width="1014" alt="Screenshot 2023-08-09 at 12 18 07" src="https://github.com/braze-inc/braze-flutter-sdk/assets/118147398/5426d5e2-39d0-446f-87f2-dcc7c6c12151">

**Comment by Shatha-Naami** [comment]
@favazHF same thing here!

**Comment by hokstuff** [comment]
Hi @favazHF @Shatha-Naami,

The best way to get more detailed support on this issue is to contact our Support team by emailing support@braze.com. You should then provide information on how to reproduce this issue in Braze Flutter sample app, including a campaign you used and the steps to repro.

For Deep linking, clicking on the button will trigger the [appropriate Apple-provided handler](https://www.braze.com/docs/developer_guide/push_notifications/deep_linking?tab=swift#:~:text=Step%203%3A-,Implement%20a%20handler,-After%20activating%20your), so if it is properly set up to accept the deep link, then the method [`[application:openURL:options:]`](https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623112-application?language=objc) should be called. If it isn't called, that means there is an integration issue preventing the appropriate iOS method from getting called.
