### ISSUE TITLE
In App Messages image url not valid (v4.1.0)

### ISSUE THREAD

**Issue by JordyLangen** [braze-inc/braze-flutter-sdk#49]
After updating to 4.1.0 we see the following issue popping up in our Sentry monitoring:

```
Invalid argument(s): No host specified in URI file:///var/mobile/Containers/Data/Application/224B0CEF-F064-449F-B78D-EE0F12A5B4A5/Library/Caches/com.braze.inappmessage/a2bec79c9885bb2172e0577de4f09b00a034b0ac47d627a89673c977672e4d92/f3fe2c8ef3347780b65da4969640ca326a6b4bd9468673f2a135f2d4ac9217c7.jpg
```

```
Crashed in non-app:
http_impl.dart in _HttpClient._openUrl
System
io_client.dart in IOClient.send at line 57 within http
In App
file_service.dart in HttpFileService.get at line 35 within flutter_cache_manager
In App
web_helper.dart in WebHelper._download at line 121 within flutter_cache_manager
In App
web_helper.dart in WebHelper._updateFile at line 103 within flutter_cache_manager
In App
Called from:
<asynchronous suspension>
System
web_helper.dart in WebHelper._downloadOrAddToQueue at line 71 within flutter_cache_manager
```

We also see the following HTTP requests being made beforehand (which could also be content cards):
![afbeelding](https://user-images.githubusercontent.com/418977/232716325-39716797-8a18-4bf0-9a8b-ff369948f64e.png)

It only happens on iOS, we do not see a similar issue on Android.

**Comment by JordyLangen** [comment]
It's (probably) this campaign:

https://dashboard-03.braze.com/engagement/campaigns/641c62574f24c9031c485acb/5b640d667dea0d20180ce281?locale=en

**Comment by JordyLangen** [comment]
@hokstuff the reference of `flutter_cache_manager` is there because we use `CachedNetworkImage` when showing the images from braze.

We have not changed any logic with regards to our in app message integration, and the `flutter_cache_manager` has not been updated since 25 feb 2022 in our codebase. The only difference between now and the last time is the braze plugin and it's native counterpart updates. Aside from that the issue is reproducable 100% of the time so I highly doubt it's a caching issue.

You are provided with steps to reproduce over email (I assume as you are aware about the support ticket).

**Comment by JordyLangen** [comment]
After a chat we learned that there was a breaking change as in app message images are cached by the SDK and thus return a path to a file locally on the device instead of the hosted image url.

We've made the appropriate changes and are now getting this:

![afbeelding](https://user-images.githubusercontent.com/418977/233966153-04a432c5-f562-4dac-b059-476a36707d0c.png)

Any ideas?

**Comment by lowip** [comment]
Hi Jordy,

This last issue comes from our Flutter SDK being unable to determine the lifetime of the in-app message and discarding the local asset files earlier than expected.

As mentioned during our call, the long term solution we are currently working on will ensure that you can get access to the data models containing remote URLs. This should allow you to revert to your original implementation.

The fix should be out in the coming days and we'll update here once it's available.

**Comment by JordyLangen** [comment]
@lowip could you perhaps elaborate on how the caching mechanic works? I personally would've expected that the cached images would have a longer time to live than a couple of (milli)seconds.

**Comment by lowip** [comment]
Hi @JordyLangen,

#### Pre Braze Swift SDK 6.0.0 behavior

Internally, our SDK uses the Apple provided [`URLCache`](https://developer.apple.com/documentation/foundation/urlcache) to cache the in-app message assets. That class does not provide direct access to the cached assets on the file system, but instead the `Data` (a byte array) representation of the assets.

When triggering an in-app message, the SDK:
- Verifies that we have all the assets
- Downloads any missing assets as needed
- Put the assets in a _working_ directory associated with the in-app message
- Modify the message with the local assets URLs
- Sends the message to the user via our public API
  - Specifically the [`BrazeInAppMessagePresenter.present(message:)`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/brazeinappmessagepresenter/present(message:)) protocol method

Our SDK relies on the existence of the in-app message in memory to know when to clean up the assets. Unfortunately, after transforming the in-app message into a JSON object and sending it to the Flutter layer, the SDK no longer has a reference to the in-app message and therefore cleans up the assets. Due to the asynchronous nature of our SDK, it is possible to load and display the in-app message assets before our SDK cleans them up (the few _(milli)seconds_ you mention).

#### Braze Swift SDK 6.0.0 behavior

We have just release the Braze Swift SDK [6.0.0](https://github.com/braze-inc/braze-swift-sdk/blob/main/CHANGELOG.md#600) which addresses that issue by moving parts of the assets handling to our UI layer:
- Put the assets in a _working_ directory associated with the in-app message
- Modify the message with the local assets URLs

The [`BrazeInAppMessagePresenter.present(message:)`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/brazeinappmessagepresenter/present(message:)) protocol method now provides the in-app message before any kind of transformation (i.e. with remote asset URLs) and should allow you to revert the changes made to your integration.

On that topic, we are not sure how you currently handle the in-app messages on the native side. Our sample app provides an example using a delegate method from our UI layer (see [here](https://github.com/braze-inc/braze-flutter-sdk/blob/9c49c8ecb33d3765b2083410893c35bfc34f7071/example/ios/Runner/AppDelegate.swift#L54)) which does not prevent the Braze provided UI from displaying the message.

If you are simply interested in the in-app message data models, our recommended approach is for you to create your own class conforming to [`BrazeInAppMessagePresenter`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/brazeinappmessagepresenter/present(message:)) and assign it to the `braze.inAppMessagePresenter` property.

```swift
// Define your presenter
class FlutterInAppMessagePresenter: BrazeInAppMessagePresenter {

  func present(message: Braze.InAppMessage) {
    // Pass in-app message data to the Dart layer.
    BrazePlugin.processInAppMessage(message)
  }

}


// When initializing the SDK
braze.inAppMessagePresenter = FlutterInAppMessagePresenter()
```

#### Next steps

We are planning a release of the Braze Flutter SDK with the Braze Swift SDK 6.0.0 tomorrow. We will update this thread when it is available.

In the meantime, don't hesitate if you have any questions.

**Comment by Statyk7** [comment]
In the snippet here you extend `BrazeInAppMessagePresenter` but in the sample app code you reference, this is `BrazeInAppMessageUI`... Am I missing something??

Once you call `BrazePlugin.processInAppMessage(message)`, the In-App Message will be pass through the `inAppMessageStreamController` on the Flutter side, right?

**Comment by JordyLangen** [comment]
@hokstuff @lowip after upgrading to 5.0.0 we still see that the local asset urls do not yield any actual images. Is that expected?

**Comment by JordyLangen** [comment]
@lowip We are now using the `BrazeInAppMessagePresenter` (instead of the `BrazeInAppMessageUIDelegate`) and that works fine. 

However, we also tried with the `BrazeInAppMessageUIDelegate` (as it meant no changes on our side) but in that case we still observed this issue. We were a bit lost on whether or not we could use the `BrazeInAppMessagePresenter` as the `BrazeInAppMessageUIDelegate` allows us to discard the message (which turned out not to be an issue).

As a sidenote, the example in this repository still does use the `BrazeInAppMessageUI`: https://github.com/braze-inc/braze-flutter-sdk/blob/master/example/ios/Runner/AppDelegate.swift apparently another way of showing/handling the in-app-message which added to our confusion if we could safely use that instead of the `BrazeInAppMessageUIDelegate`

**Comment by hokstuff** [comment]
Hi @JordyLangen,

Glad to hear that you are now able to get the remote URLs in your integration.

For context, implementing via `BrazeInAppMessagePresenter` or via `BrazeInAppMessageUI` subclass (`BrazeInAppMessageUI` conforms to the `BrazeInAppMessagePresenter` protocol) and following the steps described in [the comment above](https://github.com/braze-inc/braze-flutter-sdk/issues/49#issuecomment-1533209554) will expose the `Braze.InAppMessage` data model _prior to any remote URL transformations_.

When using the `BrazeInAppMessageUIDelegate` method [as in our sample app's previous code](https://github.com/braze-inc/braze-flutter-sdk/blob/4.1.0/example/ios/Runner/AppDelegate.swift#L54) but while using Flutter SDK 5.0.0, the `inAppMessage(_:willPresent:view:)` will contain the `Braze.InAppMessage` data model _after remote URL transformation_, which is what you were seeing. We will add a specific note in the Changelog entry for 5.0.0 calling this out as well as remove any remnants of `BrazeInAppMessageUIDelegate` in the sample app AppDelegate since it is no longer used.

Hope this clears things up!

**Comment by hokstuff** [comment]
I'm closing out this thread since it appears that this specific issue around loading remote URLs for in-app messages is resolved. Please reopen this thread if this isn't the case or follow up in Support or if new issues arise.

Thank you!
