### ISSUE TITLE
Upgrade to 5.0.0 seems broken

### ISSUE THREAD

**Issue by JordyLangen** [braze-inc/braze-flutter-sdk#51]
After updating our plugin dependency to 5.0.0 and running `pod install –repo-update` I get the following:

```
[!] CocoaPods could not find compatible versions for pod "BrazeLocation":
  In snapshot (Podfile.lock):
    BrazeLocation (= 5.12.0, ~> 5.12.0)

  In Podfile:
    braze_plugin (from `.symlinks/plugins/braze_plugin/ios`) was resolved to 5.0.0, which depends on
      BrazeLocation (~> 6.0.0)


You have either:
 * changed the constraints of dependency `BrazeLocation` inside your development pod `braze_plugin`.
   You should run `pod update BrazeLocation` to apply changes you've made.

```

**Comment by JordyLangen** [comment]
Removing the `Podfile.lock` seems to fix it, but that should not be needed.

**Comment by hokstuff** [comment]
Hi @JordyLangen,

In the [Cocoapods docs for `pod install`](https://guides.cocoapods.org/using/pod-install-vs-update.html#pod-install), it notes that the command will take into account the specific version inside the `Podfile.lock` instead of updating to the latest version. Adding the flag [`--repo-update` will run `pod repo update` prior to the command](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/install.rb#L32), but it will still use the `pod install` command afterwards.

In this case, it sounds like you'd want to use the [`pod update` command](https://guides.cocoapods.org/using/pod-install-vs-update.html#pod-update) to ensure that the latest version of the Braze pod is used instead of the version in `Podfile.lock`. Let us know if that resolves the issue - thanks!

**Comment by JordyLangen** [comment]
We did not seem to have to do this in the past, anyway thanks for the reply.

**Comment by Xylez01** [comment]
@hokstuff I had the same issue again when updating from 9.0.0 to 11.1.0

I ran `pod install --repo-update` and `pod repo update` and would still get a similar message. And again removing the Podfile.lock seems to fix it, but that should not be needed.

**Comment by hokstuff** [comment]
Hi @Xylez01, 

We've filed a ticket internally to investigate this. If you have further information or context around this issue, feel free to let us know. Thanks!

**Comment by hokstuff** [comment]
Hi @Xylez01,

We just discussed with the larger team, and if you are unable to use `pod update` to grab the latest Braze dependencies (e.g. you don't want to update _all_ your dependencies at once), you can try specifying the Braze dependencies with the command:
```
pod update BrazeKit BrazeUI BrazeLocation
```
If you continue to run into problems, you can also contact our Support team at support@braze.com and they will ask for more information regarding your local setup to try to resolve your issue.

Thanks!
