### ISSUE TITLE
Possible to use Braze and FirebaseMessaging same time?

### ISSUE THREAD

**Issue by Yasinilhan61** [braze-inc/braze-flutter-sdk#81]
I want to use both firebase and braze in my project, my current problem is that I get 2 push messages, one comes empty and the other comes through braze. I also save the incoming messages to the db. For this, I use firebase background handler. In the current situation, I cannot access this information in the terminate state. 

Is there a way to listen to remote message?

**Comment by hokstuff** [comment]
Hi @Yasinilhan61,

We have Braze clients who successfully use Firebase and Braze within the same project, so we know it is possible to have a working integration. If you wish to use both, you will likely need to do an advanced configuration where you have to integrate certain features with one dependency and integrate other features on the second dependency.

If you have specific questions about your integration with Braze, please contact support@braze.com with more details on what you're experiencing and they may be able to help. You will need to attach any relevant code snippets, provide specific details on your integration, and attach relevant verbose logs. If you are experiencing issues with Firebase, please contact their support team.

Since your issue has to do with your specific integration rather than more general questions, I will close out this issue and have you interface via the Support channels for more efficiency.

Thanks!

**Comment by hokstuff** [comment]
Hi @aytunch,

Please contact support@braze.com with more information on your issue. Also be sure to include relevant context including verbose logs, integration code, relevant code snippets, and steps to repro.

Thanks!
