### ISSUE TITLE
[Bug]: userInterfaceStyle is only available in iOs 12.0 or newer

### ISSUE THREAD

**Issue by hoangminhhung-addx** [braze-inc/braze-flutter-sdk#85]
### Which Platforms?

iOS

### Which Flutter Version?

3.16.9

### Which Braze Flutter SDK version?

10.1.0

### Repro Rate

100

### Steps To Reproduce

I got the problem when compiling the code with XCode version 14.5 and iOs 12. For UITraitCollection.userInterface only use for iOS 12.
![image](https://github.com/user-attachments/assets/b9357471-3e12-43b8-9243-02fd1ceed0bd)

### Expected Behavior

We should add logic to check iOS 12 above

### Actual Incorrect Behavior

Can compile with lower version

**Comment by hokstuff** [comment]
Hi @hoangminhhung-addx,

The Braze Flutter SDK depends on the [Braze Swift SDK, which supports only iOS 12.0+](https://github.com/braze-inc/braze-swift-sdk/?tab=readme-ov-file#version-information), so this is expected behavior. This means that in order to use the Flutter SDK, you will need to bump your iOS version to be 12.0+. This is also in line with Apple requiring [Xcode 15+ to submit an application to the App Store](https://developer.apple.com/ios/submit/#:~:text=Build%20with%20Xcode&text=All%20iOS%20and%20iPadOS%20apps,with%20the%20iOS%2018%20SDK.), and [Xcode 15 has a minimum deployment target of 12.0](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-15-release-notes).

Thanks!

**Comment by hoangminhhung-addx** [comment]
I updated to 12.1 and it works. Thanks
